name: CI (Linux)

on:
#  push:
#    paths:
#    - '.github/**'
#    - '3rdparty/**'
#    - 'hash/**'
#    - 'scripts/**'
#    - 'src/**'
#    - 'CMakeLists.txt'
#    - 'cmake_subdirs/**'
#  pull_request:
#    paths:
#    - '.github/**'
#    - '3rdparty/**'
#    - 'hash/**'
#    - 'scripts/**'
#    - 'src/**'
#    - 'CMakeLists.txt'
#    - 'cmake_subdirs/**'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ninja-build
      - name: Build
        run: |
          cmake -G Ninja
          ninja
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
         fallback: test
      - uses: actions/upload-artifact@master
        with:
          name: chdman-linux-${{ steps.previoustag.outputs.tag }}
          path: chdman
          
